BINDIR=${EZDIR_HOME}/bin
LIBDIR=-L${EZDIR_HOME}/lib -L${ORACLE_HOME}/lib
BINARY=EzSafReader
OBJFILE=ezsafreader.o
SOURCE=ezsafreader.cpp
OBJFILE1=ezsafsemtable.o
SOURCE1=ezsafsemtable.cpp
OBJFILE2=ezsafreaderdb.o
SOURCE2=ezsafreaderdb.c
SOURCEPC=ezsafreaderdb.pc
LIBLIST=-lezdebug_util -lezsigutil -leztaskutil -lezchannelutil -leznetworkutil -lezcfg_util -lezdbutil -lpthread -lclntsh -lezreplayutil -lezchanneltools -lezeventutil -lezeventtable -leztxnrefselectutil -lezsafformatutil
INCLUDEDIR=${EZDIR_HOME}/include
OINCLUDEDIR=${ORACLE_HOME}/precomp/public

${BINARY}	:	${OBJFILE} ${OBJFILE2}
			g++ ${OBJFILE} ${OBJFILE2} ${LIBDIR} ${LIBLIST} -o ${BINARY}	

${OBJFILE}		:	${SOURCE}
					g++ -c ${SOURCE} -I${INCLUDEDIR}

${OBJFILE2}		:	${SOURCEPC}
					proc ${SOURCEPC}
					cc -c ${SOURCE2} -I${INCLUDEDIR} -I${OINCLUDEDIR}
			
install		:
			mv ${BINARY} ${BINDIR}

clean		:
			rm *.o
			rm tp*
				
