BINDIR=${EZDIR_HOME}/bin
LIBDIR=-L${EZDIR_HOME}/lib -L${ORACLE_HOME}/lib
BINARY=EzEchoMgr
OBJFILE=ezechomanager.o
SOURCE=ezechomanager.cpp
OBJFILE1=ezechointervaltable.o
SOURCE1=ezechointervaltable.cpp
OBJFILE2=ezechomanagerdb.o
SOURCE2=ezechomanagerdb.c
SOURCEPC=ezechomanagerdb.pc
OINCLUDEDIR=${ORACLE_HOME}/precomp/public
LIBLIST=-lezdebug_util -lezsigutil -leztaskutil -lezchannelutil -lezcfg_util -lezcommutil -leznetworkutil -lezdbutil -lezdatetimeutil -lezechoutil -lclntsh
INCLUDEDIR=${EZDIR_HOME}/include

${BINARY}	:	${OBJFILE1} ${OBJFILE2} ${OBJFILE} 
			g++ ${OBJFILE1} ${OBJFILE2} ${OBJFILE} ${LIBDIR} ${LIBLIST} -o ${BINARY}	

${OBJFILE}	:	${SOURCE}
			g++ -c ${SOURCE} -I${INCLUDEDIR}

${OBJFILE1}	:	${SOURCE1}
			g++ -c ${SOURCE1} -I${INCLUDEDIR}
			
${OBJFILE2}	:	${SOURCEPC}
			proc ${SOURCEPC}
			cc -c ${SOURCE2} -I${INCLUDEDIR} -I${OINCLUDEDIR}
			
			
install		:
			mv ${BINARY} ${BINDIR}

clean		:
			rm *.o
			rm tp*
				
