BINDIR=${EZDIR_HOME}/bin
LIBDIR=${EZDIR_HOME}/lib
OBJFILE=ezmsgrouterutil.o
SOURCE=ezmsgrouterutil.cpp
INCLUDEDIR=${EZDIR_HOME}/include

${OBJFILE}	:	${SOURCE}
			g++ -c ${SOURCE} -I${INCLUDEDIR}
